version: '3'

services:
  mssql:
    build: ./src/database
    ports:
      - 1433:1433
    volumes:
      - vmssql:/var/opt/mssql
    networks:
      - default
    
  api-dev:
    container_name: authentication-api-dev
    image: authentication-api-dev:1.0.0
    depends_on:
      - mssql
    links:
      - "mssql:mssql"
    env_file:
      - ./.env
    build: 
      context: .
      target: development
      dockerfile: ./dockerfile
    command: yarn run start:debug
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

  api-prod:
    container_name: authentication-api-prod
    image: authentication-api-prod:1.0.0
    depends_on:
      - mssql
    links:
      - "mssql:mssql"
    env_file:
      - ./.env
    build: 
      context: .
      target: production
      dockerfile: ./dockerfile
    command: yarn run start:prod
    ports:
      - 4001:4001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

volumes:
  vmssql: