version: '3'

services:
  mssql:
    build:
      context: .
      dockerfile: ./src/database/Dockerfile
    ports:
      - 1433:1433
    volumes:
      - vmssql:/var/opt/mssql
    networks:
      - default
    restart: always
    
  api-dev:
    container_name: authentication-api-dev
    image: authentication-api-dev:1.0.0
    depends_on:
      - mssql
    env_file:
      - ./.env
    build: 
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn run start:debug
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
    restart: always

  api-prod:
    container_name: authentication-api-prod
    image: authentication-api-prod:1.0.0
    depends_on:
      - mssql
    env_file:
      - ./.env
    build: 
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: yarn run start:prod
    ports:
      - 4001:4001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default
    restart: always

volumes:
  vmssql: